name: Dispatch Restrict External PRs

on:
  pull_request_target:

jobs:
  close-external-prs:
    uses: crickets-and-comb/shared/.github/workflows/block_outside_PRs.yml@main
    with:
      ALLOWED_USERS: "KalebCoberly"
    secrets:
      ORG_READ_TOKEN: ${{ secrets.ORG_READ_TOKEN }}